# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'CoffeeAnyone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoffeeAnyone

  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'
  pod 'Firebase/MLVisionFaceModel'
  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionLabelModel'

  target 'CoffeeAnyoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoffeeAnyoneUITests' do
    # Pods for testing
  end

end
