# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'chatView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chatView
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

	

  target 'chatViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chatViewUITests' do
    # Pods for testing
  end

end


